name: Assign reviewers to dependabot PRs

on:
  pull_request:
    types: [ready_for_review]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    permissions:
      pull-requests: write

    steps:
      - name: Assign me as reviewer
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: gh pr review-requests add $PR_NUMBER @Torch3333

