name: Assign reviewers to dependabot PRs

on:
  pull_request:
    types: [opened]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    permissions:
      pull-requests: write

    steps:
      - name: Logs
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Event: ${{ github.event_name }}"
          echo "Event Action: ${{ github.event.action }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"

      - name: Assign ScalarDB team as reviewers for Dependabot PRs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPOSITORY: ${{ github.action_repository }}
        run: gh pr edit $PR_NUMBER --add-reviewer Torch3333 --repo $REPOSITORY

