name: Auto-PR

on:
  pull_request:
    branches:
      - main
      - "[0-9]+"
      - "[0-9]+.[0-9]+"
    types:
      - closed

jobs:
  if_merged:
    uses: torch3333/scalardb/actions/.github/workflows/auto-pr-reusable.yaml@add-auto-pr
    secrets: inherit
    with:
      project_base_name: "Auto-pr test"

