name: Auto-PR

on:
  pull_request:
    branches:
      - main
      - "[0-9]+"
      - "[0-9]+.[0-9]+"
    types:
      - closed
env:
  VERSION: "auto-pr@v1"
jobs:
  if_merged:
    uses: torch3333/scalardb/.github/workflows/auto-pr-reusable.yaml@auto-pr@v1
    secrets: inherit
    with:
      version: auto-pr@v1
      project_base_name: "Auto-pr test"

